feature_flags:
  storage:
    type: doctrine  # Peut être 'doctrine', 'yaml' ou 'json'

  doctrine:
    enabled: true

  yaml:
    enabled: false
    path: '%kernel.project_dir%/config/feature_flags.yaml'

  json:
    enabled: false
    path: '%kernel.project_dir%/config/feature_flags.json'